### ISSUE TITLE
Failing to compile on macOS with error ```E0433```

### ISSUE THREAD

**Issue by KT819GM** [olback/library-loader#32]
Rust is installed using: ```curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh``` Compilation fails with:
```
error[E0433]: failed to resolve: could not find `line` in `std`
  --> src/main.rs:38:87
   |
38 |                 eprintln!("{}#{}: Error checking for updates: {}", std::file!(), std::line!(), e);
   |                                                                                       ^^^^ could not find `line` in `std`

error: aborting due to 41 previous errors
```
Is this problem with environment or with source itself?
Thank you

**Comment by olback** [comment]
Could you post the output of `rustup show` and `rustup component list | grep installed`?

**Comment by KT819GM** [comment]
Hi, sure:
```rustup show

Default host: x86_64-apple-darwin
rustup home:  /Users/user/.rustup

stable-x86_64-apple-darwin (default)
rustc 1.37.0 (eae3437df 2019-08-13)

rustup component list | grep installed

cargo-x86_64-apple-darwin (installed)
rust-docs-x86_64-apple-darwin (installed)
rust-std-x86_64-apple-darwin (installed)
rustc-x86_64-apple-darwin (installed)```

**Comment by olback** [comment]
Try `rustup install stable` and `rustup update`. I tried cloning and compiling with the latest rust version just now and had no issues.

**Comment by KT819GM** [comment]
```rustup install stable``` - that helped. Next time I will try not to be potato and to dig bit deeper into problem before submitting bug / question. Thank you

**Comment by olback** [comment]
No problem!
