### ISSUE TITLE
handle error when componentsearchengine's terms and conditions change

### ISSUE THREAD

**Issue by tobiasvogel** [olback/library-loader#42]
Every now and then, the Samacsys' componentsearchengines Terms and Conditions change. Upon login on their site, one is prompted to read and agree/disagree to their updated Terms and Conditions.

The library loader failed with the error "Error downloading file: Could not determine content type". It took me quite some time to figure out what the problem was, as i wrongly suspected a bug in the library loader.

A simple solution was to implement a check, as the model.php (as in const 'COMPONENT_SEARCH_ENGINE_URL') simply returns this plain text string in such case:

`Error: Our terms and conditions have changed. You need to log in at https://componentsearchengine.com and accept the new terms before downloading models.`

**Comment by olback** [comment]
Thanks for reporting this. This is something that never even crossed my mind.

**Comment by olback** [comment]
For this error to occur, componentsearchengine.com has to respond with a status of OK, but the status obviously isn't ok...

**Comment by olback** [comment]
Note added in last version.
