### ISSUE TITLE
Error downloading file: 401 Unauthorized

### ISSUE THREAD

**Issue by abferm** [olback/library-loader#52]
Had been working fine until today. Now I get a 401 Unauthorized error when I try to run. Credentials are fine, I can log into componentsearchengine.com.

**Comment by tobiasvogel** [comment]
Same problem here since a couple of days...

**Comment by olback** [comment]
The `TRY_AUTH_URL` is only used to very the password on login. No state is stored after using it. Every request contains username/password.

As for why we get a 401, I have no idea. I'll look into it.

**Comment by olback** [comment]
Turns out that `COMPONENT_SEARCH_ENGINE_URL` has to use HTTPS. Fixed in next release.
