### ISSUE TITLE
gui fails to compile on macos

### ISSUE THREAD

**Issue by neilthomson** [olback/library-loader#54]
I have a fresh install of rust toolchain (not a rust dev)
cli compiled OK
building gui failed at with 

```
   ...
   Compiling glib-macros v0.10.0
   Compiling gdk-sys v0.10.0
   Compiling atk-sys v0.10.0
   Compiling gtk-sys v0.10.0
   Compiling library-loader-gui v0.2.2 (/Users/neil/code/library-loader/ll-gui)
error: failed to run custom build command for `glib-sys v0.10.0`

Caused by:
  process didn't exit successfully: `/Users/neil/code/library-loader/target/release/build/glib-sys-a440839a206d2de1/build-script-build` (exit code: 1)
--- stderr
Failed to run `"pkg-config" "--libs" "--cflags" "glib-2.0" "glib-2.0 >= 2.42"`: No such file or directory (os error 2)

warning: build failed, waiting for other jobs to finish...
error: build failed
```

I have pkgbuild  pkgutil in my path but no pkg-config - I don't knpw anything about packaging but thought I'd flag the error, great project!

**Comment by olback** [comment]
You also need glib installed. You can install it with homebrew I think. I don't have a Mac so I can't really test this.

**Comment by neilthomson** [comment]
Thought I'd tried that for some reason, but anywho, I then had a fun game of whack a mole but eventually found all the missing packages and installed with brew and it compiled :)

other mac users will need to ```brew install glib pkg-config cairo pango atk gdk-pixbuf gtk+3```

The gui then runs from the command line - the install script won't work on a mac, I didn't run it but they look like linux specific paths, so the gui is missing the svg graphics but no biggie. Then I started actually using the cli and that will work for me, thanks for porting! I use Eagle so great to have this without booting up my windows machine. Maybe at some point I can help get this working as a brew package but don't know enough about that at this stage to write the scripts but happy to test.

How do you actually run the pre-compiled download? I couldn't ```$./library-loader-gui``` - do I need to invoke with rust or something? Sorry if I've missed something obvious

**Comment by olback** [comment]
The pre-built binary is unfortunately Linux only. I feel I could have done a better job documenting this thing.
