### ISSUE TITLE
How do you launch the app?

### ISSUE THREAD

**Issue by harry-finch** [olback/library-loader#61]
Hi,

Forgive my ignorance... I have successfully build the ll-gui, everything went well, but now I don't know how to launch the app. I have tried running library-loader-gui.desktop but it just launches GIMP...

I'm on MacOS 11.3.2 (Big Sur).

Many thanks for your help!
Harold

**Comment by olback** [comment]
I haven't put much thought into the Mac experience since I have no way of testing it. I'm not sure how gimp got launched though.

**Comment by tobiasvogel** [comment]
I could look into this in the next couple of days if you want me to, but I needed to know exactly how you built it and how you tried to launch it?

**Comment by harry-finch** [comment]
Hi, thanks for your feedbacks! It was my first time building such a project so I didn't know the app would build to the "target" directory... and now it works fine!! Many thanks for such a useful app by the way :)
