### ISSUE TITLE
Multiple output formats or 3d checkbox/button

### ISSUE THREAD

**Issue by pauluzs** [olback/library-loader#62]
Is outputting both format Kicad and format 3D possible in the current release version ?

Tried comma and space separation for  `format = 'kicad, 3d'` no luck
Tried launching multiple instances of `library-loader-gui` also no luck

As for now workflow is: output zip format, extract 3D from zip, extract KiCad from zip, delete zip.
Maybe it would be possible to add a output 3D checkbox/radiobutton besides the format dropdown?

**Comment by olback** [comment]
The plan is to rewrite parts of the program to support any number of formats saved to different locations. 

You can run two instances of `library-loader-cli` with a custom config path specified with the `-c` option.
